title: "Screen Nutrition"
email: ""
description: "Screen Nutrition website migrated to Jekyll"
baseurl: "" # no subpath when using custom domain
url: "https://screennutrition.org" # custom domain
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed

exclude:
  - page_captures
  - .venv
  - get-pip.py
